version: 2
updates:
  - package-ecosystem: github-actions
    directory: "/"
    target-branch: master
    schedule:
      interval: weekly
      day: saturday
      time: "12:00"
      timezone: Asia/Tokyo
    open-pull-requests-limit: 10
    reviewers:
      - mintak21
