version: 2.1

orbs:
  terraform: ovotech/terraform@1.6.6

workflows:
  version: 2
  ci:
    jobs:
      - fmt_validate

jobs:
  fmt_validate:
    executor: terraform/terraform-0_12
    steps:
      - checkout
      - terraform/fmt-check:
          path: files
      - terraform/validate:
          path: files
