name: "Terraform Continious CI/CD"

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  terraform-ci:
    name: "Terraform"
    strategy:
      matrix:
        env: [practice, development]

    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
        working-directory: ./environments/aws/${{ matrix.env }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: ${{ matrix.env }} Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }} # for development

      - name: Terraform Init Env:${{ matrix.env }}
        run: terraform init

      - name: Terraform Format Check Env:${{ matrix.env }}
        run: terraform fmt -check

      - name: Terraform Validate Env:${{ matrix.env }}
        run: terraform validate

      - name: TFLint Env:${{ matrix.env }}
        uses: reviewdog/action-tflint@master
        with:
          github_token: ${{ secrets.github_token }}

      - name: Terraform Plan Env:${{ matrix.env }}
        run: terraform plan
      # - name: Terraform Apply
      #   if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      #   run: terraform apply -auto-approve
