name: "Terraform Continious Custom CI"

on:
  push:
  # どうもGithub-Actions上でtfnotifyはpushでないと動かない様子
  #   branches:
  #     - master
  #     - development
  # pull_request:

jobs:
  terraform-ci:
    name: "Terraform CI"

    runs-on: ubuntu-latest

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
        working-directory: .

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1

      - name: Install Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }} # for development

      - name: Install Dependent Packages
        run: ./scripts/ci/install_packages.sh

      - name: Check Environment Values
        run: echo "REPOSITORY is ${GITHUB_REPOSITORY} ID is ${GITHUB_RUN_ID} Revision is ${GITHUB_SHA}"

      - name: Terraform Format Check
        run: ./scripts/ci/format.sh

      - name: Terraform Validate
        run: ./scripts/ci/validate.sh

      - name: Terraform Lint(Deep AWS API)
        run: ./scripts/ci/lint_aws.sh

      - name: Terraform Plan
        run: ./scripts/ci/plan.sh
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      # - name: Terraform Apply
      #   if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      #   run: terraform apply -auto-approve
